# Generated by Django 2.0 on 2019-03-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_content', models.CharField(max_length=280)),
                ('tweet_intro', models.CharField(blank=True, max_length=31)),
                ('publish_status', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField()),
                ('user_id', models.IntegerField(default=0)),
            ],
        ),
    ]
