# Generated by Django 2.0 on 2019-03-29 17:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yohakuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 29, 17, 12, 8, 54264, tzinfo=utc)),
        ),
    ]
